### ISSUE TITLE
String error

### ISSUE THREAD

**Issue by aidnzz** [Fahad-M/Neutron#1]
https://github.com/Fahad-M/Neutron/blob/9e0fe8e8f34f016faa35f96563852b8a9f8ac39b/neutron_core.py#L43-L48

If an exception is thrown it sets status to a string but returns 'status.content' and content is not a member of str

**Comment by quantumcore** [comment]
Thanks a ton for reporting this Issue. I guess I didn't try running it with No Network. I'll try more tests. 
This is now fixed. 

I removed the Update feature. Seems it was a nice idea but at the same time, For people who download it a Big Bug. I will add it completely fixing the problem soon. 

I thank you soo much for reporting this Bug.

**Comment by quantumcore** [comment]
Yeah.
